/**
 * @type {import('node-pg-migrate').ColumnDefinitions | undefined}
 */
export const shorthands = undefined;

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
export const up = (pgm) => {
    pgm.sql(
        `
        CREATE TABLE IF NOT EXISTS attachments (
            attachment_id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
            name VARCHAR(200) NOT NULL,
            url VARCHAR(300) NOT NULL,
            type VARCHAR(30) NOT NULL
        );

        CREATE TABLE IF NOT EXISTS users (
            user_id INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
            email VARCHAR(40),
            country_code CHAR(2) DEFAULT 'IN' NOT NULL,
            phone_number VARCHAR(20) UNIQUE NOT NULL,
            password TEXT NOT NULL,
            username VARCHAR(200) UNIQUE NOT NULL,
            profile_pic_id INT DEFAULT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            deleted_at TIMESTAMP DEFAULT NULL,
            PRIMARY KEY(user_id),
            CONSTRAINT fk_users_attachment_id 
                FOREIGN KEY(profile_pic_id) 
                REFERENCES attachments(attachment_id)
                ON DELETE SET NULL
        );

        CREATE TYPE user_signup_verification_status AS ENUM('USER_CREATED', 'OTP_SENT', 'OTP_VERIFIED', 'OTP_EXPIRED', 'OTP_RESENT', 'FAILED');

        CREATE TABLE IF NOT EXISTS user_signup_verifications (
            verification_id INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
            user_id INT NOT NULL,
            verification_status user_signup_verification_status,
            created_at TIMESTAMP DEFAULT NOW(),
            updated_at TIMESTAMP DEFAULT NOW(),
            no_of_attempts INT DEFAULT 0,
            PRIMARY KEY(verification_id),
            CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id)
        );
        
        CREATE TYPE device_type AS ENUM('Android phone', 'Tablet', 'IOS Phone', 'Web browser');

        CREATE TABLE IF NOT EXISTS user_devices (
            user_id INT NOT NULL,
            device_id INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL UNIQUE,
            name VARCHAR(100) NOT NULL,
            type device_type,
            PRIMARY KEY(user_id, device_id),
            CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE RESTRICT
        );

        CREATE TABLE IF NOT EXISTS expense_category (
            id INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
            name VARCHAR(100) NOT NULL UNIQUE,
            thumbnail_id INT DEFAULT NULL,
            description VARCHAR(200),
            CONSTRAINT fk_thumbnail_id
                FOREIGN KEY(thumbnail_id)
                REFERENCES attachments(attachment_id)
                ON DELETE SET NULL
        );

        CREATE TYPE recurring_expense_freq AS ENUM('day', 'month', 'week', 'year');

        CREATE TYPE expense_type AS ENUM('Debit', 'Credit');

        CREATE TABLE IF NOT EXISTS expense (
            expense_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
            user_id INT NOT NULL,
            name VARCHAR(150) NOT NULL,
            category_id INT NOT NULL,
            notes VARCHAR(300),
            amount NUMERIC CHECK(amount > 0),
            currency CHAR(1) NOT NULL,
            recurring_frequency recurring_expense_freq,
            bill_image_url VARCHAR(200),

            type expense_type NOT NULL,

            created_at TIMESTAMP DEFAULT NOW(),
            created_by INT NOT NULL,
            deleted_at TIMESTAMP DEFAULT NULL,
            
            paid_on TIMESTAMP,

            CONSTRAINT fk_cat_id FOREIGN KEY(category_id) REFERENCES expense_category(id) ON DELETE RESTRICT,
            CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE RESTRICT
        );

        CREATE TYPE expense_actions AS ENUM('CREATED', 'AMOUNT_UPDATED', 'CURRENCY_UPDATED', 'TYPE_UPDATED', 'ITEMS_LIST_UPDATED', 'PAID', 'DELETED');

        CREATE TABLE IF NOT EXISTS expense_history (
            log_id INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
            expense_id BIGINT NOT NULL,
            action expense_actions NOT NULL,
            action_done_on TIMESTAMP NOT NULL DEFAULT NOW(),
            action_done_by INT NOT NULL,
            CONSTRAINT fk_expense_id FOREIGN KEY(expense_id) REFERENCES expense(expense_id) ON DELETE RESTRICT,
            CONSTRAINT fk_action_done_by FOREIGN KEY(action_done_by) REFERENCES users(user_id) ON DELETE RESTRICT
        );
        `
    )
};

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
export const down = (pgm) => {
    pgm.sql(`
        DROP TABLE IF EXISTS attachments, users, user_devices, expense_category, expense, user_transactions, user_signup_verifications, expense_history CASCADE;
        DROP TYPE IF EXISTS device_type, recurring_expense_freq, expense_type, user_signup_verification_status, expense_actions;
    `)
};

// CREATE TABLE IF NOT EXISTS user_transactions (
//             user_expense_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
//             user_id INT NOT NULL,
//             expense_id BIGINT NOT NULL,
//             is_recurring_expense BOOLEAN DEFAULT false,
//             transaction_type expense_type NOT NULL,
//             amount NUMERIC CHECK(amount > 0),
//             CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE RESTRICT,
//             CONSTRAINT fk_expense_id FOREIGN KEY(expense_id) REFERENCES expense(expense_id) ON DELETE RESTRICT
//         );