packages:
  - types
  - utils
  - "apps/frontend/et-web"
  - "apps/backend/*"
  - "apps/frontend/et-web/*"
  - "types/*"
  - "utils/*"
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
catalog:
  typescript: 5.7.3
  ts-node: ^10.9.2
  "@types/node": 25.3.5