drop extension if exists "pg_net";

create type "public"."device_type" as enum ('Android phone', 'Tablet', 'IOS Phone', 'Web browser');

create type "public"."expense_actions" as enum ('CREATED', 'AMOUNT_UPDATED', 'CURRENCY_UPDATED', 'TYPE_UPDATED', 'ITEMS_LIST_UPDATED', 'PAID', 'DELETED');

create type "public"."expense_type" as enum ('Debit', 'Credit');

create type "public"."recurring_expense_freq" as enum ('day', 'month', 'week', 'year');

create type "public"."user_signup_verification_status" as enum ('USER_CREATED', 'OTP_SENT', 'OTP_VERIFIED', 'OTP_EXPIRED', 'OTP_RESENT', 'FAILED');


  create table "public"."attachments" (
    "attachment_id" integer generated by default as identity not null,
    "name" character varying(200) not null,
    "url" character varying(300) not null,
    "type" character varying(30) not null
      );


alter table "public"."attachments" enable row level security;


  create table "public"."expense" (
    "expense_id" bigint generated always as identity not null,
    "user_id" integer not null,
    "name" character varying(150) not null,
    "category_id" integer not null,
    "notes" character varying(300),
    "amount" numeric,
    "country_code" character varying(10) not null,
    "recurring_frequency" public.recurring_expense_freq,
    "bill_image_url" character varying(200),
    "type" public.expense_type not null,
    "created_at" timestamp without time zone default now(),
    "deleted_at" timestamp without time zone,
    "paid_on" timestamp without time zone
      );


alter table "public"."expense" enable row level security;


  create table "public"."expense_category" (
    "id" integer generated always as identity not null,
    "name" character varying(100) not null,
    "thumbnail_id" integer,
    "description" character varying(200)
      );


alter table "public"."expense_category" enable row level security;


  create table "public"."expense_history" (
    "log_id" bigint generated always as identity not null,
    "expense_id" bigint not null,
    "action" public.expense_actions not null,
    "action_done_on" timestamp without time zone not null default now(),
    "action_done_by" integer not null
      );


alter table "public"."expense_history" enable row level security;


  create table "public"."user_devices" (
    "user_id" integer not null,
    "device_id" integer generated always as identity not null,
    "name" character varying(100) not null,
    "type" public.device_type
      );


alter table "public"."user_devices" enable row level security;


  create table "public"."user_signup_verifications" (
    "verification_id" integer generated always as identity not null,
    "user_id" integer not null,
    "verification_status" public.user_signup_verification_status,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now(),
    "no_of_attempts" integer default 0
      );


alter table "public"."user_signup_verifications" enable row level security;


  create table "public"."user_transactions" (
    "user_expense_id" bigint generated always as identity not null,
    "user_id" integer not null,
    "expense_id" bigint not null,
    "is_recurring_expense" boolean default false,
    "transaction_type" public.expense_type not null,
    "amount" numeric
      );


alter table "public"."user_transactions" enable row level security;


  create table "public"."users" (
    "user_id" integer generated always as identity not null,
    "email" character varying(40),
    "country_code" character(2) not null default 'IN'::bpchar,
    "phone_number" character varying(20) not null,
    "password" text not null,
    "username" character varying(200) not null,
    "profile_pic_id" integer,
    "created_at" timestamp without time zone not null default now(),
    "deleted_at" timestamp without time zone
      );


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX attachments_pkey ON public.attachments USING btree (attachment_id);

CREATE UNIQUE INDEX expense_category_name_key ON public.expense_category USING btree (name);

CREATE UNIQUE INDEX expense_category_pkey ON public.expense_category USING btree (id);

CREATE UNIQUE INDEX expense_history_pkey ON public.expense_history USING btree (log_id);

CREATE UNIQUE INDEX expense_pkey ON public.expense USING btree (expense_id);

CREATE UNIQUE INDEX user_devices_device_id_key ON public.user_devices USING btree (device_id);

CREATE UNIQUE INDEX user_devices_pkey ON public.user_devices USING btree (user_id, device_id);

CREATE UNIQUE INDEX user_signup_verifications_pkey ON public.user_signup_verifications USING btree (verification_id);

CREATE UNIQUE INDEX user_transactions_pkey ON public.user_transactions USING btree (user_expense_id);

CREATE UNIQUE INDEX users_phone_number_key ON public.users USING btree (phone_number);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

alter table "public"."attachments" add constraint "attachments_pkey" PRIMARY KEY using index "attachments_pkey";

alter table "public"."expense" add constraint "expense_pkey" PRIMARY KEY using index "expense_pkey";

alter table "public"."expense_category" add constraint "expense_category_pkey" PRIMARY KEY using index "expense_category_pkey";

alter table "public"."expense_history" add constraint "expense_history_pkey" PRIMARY KEY using index "expense_history_pkey";

alter table "public"."user_devices" add constraint "user_devices_pkey" PRIMARY KEY using index "user_devices_pkey";

alter table "public"."user_signup_verifications" add constraint "user_signup_verifications_pkey" PRIMARY KEY using index "user_signup_verifications_pkey";

alter table "public"."user_transactions" add constraint "user_transactions_pkey" PRIMARY KEY using index "user_transactions_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."expense" add constraint "expense_amount_check" CHECK ((amount > (0)::numeric)) not valid;

alter table "public"."expense" validate constraint "expense_amount_check";

alter table "public"."expense" add constraint "fk_cat_id" FOREIGN KEY (category_id) REFERENCES public.expense_category(id) ON DELETE RESTRICT not valid;

alter table "public"."expense" validate constraint "fk_cat_id";

alter table "public"."expense" add constraint "fk_user_id" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE RESTRICT not valid;

alter table "public"."expense" validate constraint "fk_user_id";

alter table "public"."expense_category" add constraint "expense_category_name_key" UNIQUE using index "expense_category_name_key";

alter table "public"."expense_category" add constraint "fk_thumbnail_id" FOREIGN KEY (thumbnail_id) REFERENCES public.attachments(attachment_id) ON DELETE SET NULL not valid;

alter table "public"."expense_category" validate constraint "fk_thumbnail_id";

alter table "public"."expense_history" add constraint "fk_action_done_by" FOREIGN KEY (action_done_by) REFERENCES public.users(user_id) ON DELETE RESTRICT not valid;

alter table "public"."expense_history" validate constraint "fk_action_done_by";

alter table "public"."expense_history" add constraint "fk_expense_id" FOREIGN KEY (expense_id) REFERENCES public.expense(expense_id) ON DELETE RESTRICT not valid;

alter table "public"."expense_history" validate constraint "fk_expense_id";

alter table "public"."user_devices" add constraint "fk_user_id" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE RESTRICT not valid;

alter table "public"."user_devices" validate constraint "fk_user_id";

alter table "public"."user_devices" add constraint "user_devices_device_id_key" UNIQUE using index "user_devices_device_id_key";

alter table "public"."user_signup_verifications" add constraint "fk_user_id" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE not valid;

alter table "public"."user_signup_verifications" validate constraint "fk_user_id";

alter table "public"."user_transactions" add constraint "fk_expense_id" FOREIGN KEY (expense_id) REFERENCES public.expense(expense_id) ON DELETE RESTRICT not valid;

alter table "public"."user_transactions" validate constraint "fk_expense_id";

alter table "public"."user_transactions" add constraint "fk_user_id" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE RESTRICT not valid;

alter table "public"."user_transactions" validate constraint "fk_user_id";

alter table "public"."user_transactions" add constraint "user_transactions_amount_check" CHECK ((amount > (0)::numeric)) not valid;

alter table "public"."user_transactions" validate constraint "user_transactions_amount_check";

alter table "public"."users" add constraint "fk_users_attachment_id" FOREIGN KEY (profile_pic_id) REFERENCES public.attachments(attachment_id) ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "fk_users_attachment_id";

alter table "public"."users" add constraint "users_phone_number_key" UNIQUE using index "users_phone_number_key";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

grant delete on table "public"."attachments" to "anon";

grant insert on table "public"."attachments" to "anon";

grant references on table "public"."attachments" to "anon";

grant select on table "public"."attachments" to "anon";

grant trigger on table "public"."attachments" to "anon";

grant truncate on table "public"."attachments" to "anon";

grant update on table "public"."attachments" to "anon";

grant delete on table "public"."attachments" to "authenticated";

grant insert on table "public"."attachments" to "authenticated";

grant references on table "public"."attachments" to "authenticated";

grant select on table "public"."attachments" to "authenticated";

grant trigger on table "public"."attachments" to "authenticated";

grant truncate on table "public"."attachments" to "authenticated";

grant update on table "public"."attachments" to "authenticated";

grant delete on table "public"."attachments" to "service_role";

grant insert on table "public"."attachments" to "service_role";

grant references on table "public"."attachments" to "service_role";

grant select on table "public"."attachments" to "service_role";

grant trigger on table "public"."attachments" to "service_role";

grant truncate on table "public"."attachments" to "service_role";

grant update on table "public"."attachments" to "service_role";

grant delete on table "public"."expense" to "anon";

grant insert on table "public"."expense" to "anon";

grant references on table "public"."expense" to "anon";

grant select on table "public"."expense" to "anon";

grant trigger on table "public"."expense" to "anon";

grant truncate on table "public"."expense" to "anon";

grant update on table "public"."expense" to "anon";

grant delete on table "public"."expense" to "authenticated";

grant insert on table "public"."expense" to "authenticated";

grant references on table "public"."expense" to "authenticated";

grant select on table "public"."expense" to "authenticated";

grant trigger on table "public"."expense" to "authenticated";

grant truncate on table "public"."expense" to "authenticated";

grant update on table "public"."expense" to "authenticated";

grant delete on table "public"."expense" to "service_role";

grant insert on table "public"."expense" to "service_role";

grant references on table "public"."expense" to "service_role";

grant select on table "public"."expense" to "service_role";

grant trigger on table "public"."expense" to "service_role";

grant truncate on table "public"."expense" to "service_role";

grant update on table "public"."expense" to "service_role";

grant delete on table "public"."expense_category" to "anon";

grant insert on table "public"."expense_category" to "anon";

grant references on table "public"."expense_category" to "anon";

grant select on table "public"."expense_category" to "anon";

grant trigger on table "public"."expense_category" to "anon";

grant truncate on table "public"."expense_category" to "anon";

grant update on table "public"."expense_category" to "anon";

grant delete on table "public"."expense_category" to "authenticated";

grant insert on table "public"."expense_category" to "authenticated";

grant references on table "public"."expense_category" to "authenticated";

grant select on table "public"."expense_category" to "authenticated";

grant trigger on table "public"."expense_category" to "authenticated";

grant truncate on table "public"."expense_category" to "authenticated";

grant update on table "public"."expense_category" to "authenticated";

grant delete on table "public"."expense_category" to "service_role";

grant insert on table "public"."expense_category" to "service_role";

grant references on table "public"."expense_category" to "service_role";

grant select on table "public"."expense_category" to "service_role";

grant trigger on table "public"."expense_category" to "service_role";

grant truncate on table "public"."expense_category" to "service_role";

grant update on table "public"."expense_category" to "service_role";

grant delete on table "public"."expense_history" to "anon";

grant insert on table "public"."expense_history" to "anon";

grant references on table "public"."expense_history" to "anon";

grant select on table "public"."expense_history" to "anon";

grant trigger on table "public"."expense_history" to "anon";

grant truncate on table "public"."expense_history" to "anon";

grant update on table "public"."expense_history" to "anon";

grant delete on table "public"."expense_history" to "authenticated";

grant insert on table "public"."expense_history" to "authenticated";

grant references on table "public"."expense_history" to "authenticated";

grant select on table "public"."expense_history" to "authenticated";

grant trigger on table "public"."expense_history" to "authenticated";

grant truncate on table "public"."expense_history" to "authenticated";

grant update on table "public"."expense_history" to "authenticated";

grant delete on table "public"."expense_history" to "service_role";

grant insert on table "public"."expense_history" to "service_role";

grant references on table "public"."expense_history" to "service_role";

grant select on table "public"."expense_history" to "service_role";

grant trigger on table "public"."expense_history" to "service_role";

grant truncate on table "public"."expense_history" to "service_role";

grant update on table "public"."expense_history" to "service_role";

grant delete on table "public"."user_devices" to "anon";

grant insert on table "public"."user_devices" to "anon";

grant references on table "public"."user_devices" to "anon";

grant select on table "public"."user_devices" to "anon";

grant trigger on table "public"."user_devices" to "anon";

grant truncate on table "public"."user_devices" to "anon";

grant update on table "public"."user_devices" to "anon";

grant delete on table "public"."user_devices" to "authenticated";

grant insert on table "public"."user_devices" to "authenticated";

grant references on table "public"."user_devices" to "authenticated";

grant select on table "public"."user_devices" to "authenticated";

grant trigger on table "public"."user_devices" to "authenticated";

grant truncate on table "public"."user_devices" to "authenticated";

grant update on table "public"."user_devices" to "authenticated";

grant delete on table "public"."user_devices" to "service_role";

grant insert on table "public"."user_devices" to "service_role";

grant references on table "public"."user_devices" to "service_role";

grant select on table "public"."user_devices" to "service_role";

grant trigger on table "public"."user_devices" to "service_role";

grant truncate on table "public"."user_devices" to "service_role";

grant update on table "public"."user_devices" to "service_role";

grant delete on table "public"."user_signup_verifications" to "anon";

grant insert on table "public"."user_signup_verifications" to "anon";

grant references on table "public"."user_signup_verifications" to "anon";

grant select on table "public"."user_signup_verifications" to "anon";

grant trigger on table "public"."user_signup_verifications" to "anon";

grant truncate on table "public"."user_signup_verifications" to "anon";

grant update on table "public"."user_signup_verifications" to "anon";

grant delete on table "public"."user_signup_verifications" to "authenticated";

grant insert on table "public"."user_signup_verifications" to "authenticated";

grant references on table "public"."user_signup_verifications" to "authenticated";

grant select on table "public"."user_signup_verifications" to "authenticated";

grant trigger on table "public"."user_signup_verifications" to "authenticated";

grant truncate on table "public"."user_signup_verifications" to "authenticated";

grant update on table "public"."user_signup_verifications" to "authenticated";

grant delete on table "public"."user_signup_verifications" to "service_role";

grant insert on table "public"."user_signup_verifications" to "service_role";

grant references on table "public"."user_signup_verifications" to "service_role";

grant select on table "public"."user_signup_verifications" to "service_role";

grant trigger on table "public"."user_signup_verifications" to "service_role";

grant truncate on table "public"."user_signup_verifications" to "service_role";

grant update on table "public"."user_signup_verifications" to "service_role";

grant delete on table "public"."user_transactions" to "anon";

grant insert on table "public"."user_transactions" to "anon";

grant references on table "public"."user_transactions" to "anon";

grant select on table "public"."user_transactions" to "anon";

grant trigger on table "public"."user_transactions" to "anon";

grant truncate on table "public"."user_transactions" to "anon";

grant update on table "public"."user_transactions" to "anon";

grant delete on table "public"."user_transactions" to "authenticated";

grant insert on table "public"."user_transactions" to "authenticated";

grant references on table "public"."user_transactions" to "authenticated";

grant select on table "public"."user_transactions" to "authenticated";

grant trigger on table "public"."user_transactions" to "authenticated";

grant truncate on table "public"."user_transactions" to "authenticated";

grant update on table "public"."user_transactions" to "authenticated";

grant delete on table "public"."user_transactions" to "service_role";

grant insert on table "public"."user_transactions" to "service_role";

grant references on table "public"."user_transactions" to "service_role";

grant select on table "public"."user_transactions" to "service_role";

grant trigger on table "public"."user_transactions" to "service_role";

grant truncate on table "public"."user_transactions" to "service_role";

grant update on table "public"."user_transactions" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


